### ISSUE TITLE
licenciamento

### ISSUE THREAD

**Issue by lucasnuic** [JoaoVitorMoreiraPassos/teste_de_personalidade_perfil_de_administrador#2]
uma pergunta, poderia utilizar seu código? tenho permissão de uso e reutilização? você poderia adicionar uma licença neste repositório? 

contexto
- quero contribuir em um projeto aberto e que vai ajudar penso eu na questão de instalação ou orientação em linux.
- eu estou criando um projeto chamado aidistro que tem como objetivo melhorar a experiência de linux através de ia. e parte do que você escreveu aqui poderia me ajudar em muito em vez de eu ter que escrever o algoritmo do zero.
- uma das dúvidas de iniciantes em linux seria qual distro instalar e usar. então pensei em utilizar essa ideia aqui para esse projeto que estou desenvolvendo para supor ou ter uma hipótese de qual distro seria melhor para o usuário iniciante.
- sem uma licença neste repositório seria difícil ou impossível porque em tese sem ter uma licença seria processado, é do seu direito associar ou cria alguma com as condições por lei estabelecidas.

ficaria feliz por toda ou qualquer a essa pergunta final e que considero importante.

**Comment by JoaoVitorMoreiraPassos** [comment]
Pode sim, sem problemas

**Comment by lucasnuic** [comment]
Oi @JoaoVitorMoreiraPassos, poderia aceitar esse pr: https://github.com/JoaoVitorMoreiraPassos/teste_de_personalidade_perfil_de_administrador/pull/3?
